// Generated by Framer (1ec61f0)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getLoadingLazyAtYPosition,
  Image as Image1,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Clipboard from "/framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/r7KU3d0jY4jnUQG5z44O/Clipboard.js";
const ClipboardFonts = getFonts(Clipboard);
const cycleOrder = ["cCoFZGODb", "o20hHbw2z"];
const serializationHash = "framer-BmV2o";
const variantClassNames = {
  cCoFZGODb: "framer-v-1mmltda",
  o20hHbw2z: "framer-v-1cvn80z",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "cCoFZGODb",
  "Variant 2": "o20hHbw2z",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "cCoFZGODb",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "cCoFZGODb",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1jcr78e = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("o20hHbw2z");
  });
  const onAppear1o1rfkl = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("cCoFZGODb", true), 2e3);
  });
  useOnVariantChange(baseVariant, { o20hHbw2z: onAppear1o1rfkl });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1mmltda",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "cCoFZGODb",
          onTap: onTap1jcr78e,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { o20hHbw2z: { "data-framer-name": "Variant 2" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(Image1, {
              background: {
                alt: "",
                fit: "fill",
                intrinsicHeight: 183.2,
                intrinsicWidth: 159.2,
                loading: getLoadingLazyAtYPosition(
                  (componentViewport?.y || 0) +
                    (0 + ((componentViewport?.height || 44) - 0 - 35) / 2)
                ),
                pixelHeight: 229,
                pixelWidth: 199,
                sizes: "30px",
                src: "/images/w5TER91JYMRKSE1HTTG7Lo1MjU.png?width=199&height=229",
              },
              className: "framer-1jajtaf",
              "data-framer-name": "Ca",
              layoutDependency: layoutDependency,
              layoutId: "hrtSfVMu3",
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1ywu5on-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "KBXBQ129K-container",
                nodeId: "KBXBQ129K",
                rendersWithMotion: true,
                scopeId: "HFYYL_Y6K",
                style: { opacity: 0 },
                children: /*#__PURE__*/ _jsx(Clipboard, {
                  borderRadius: 0,
                  bottomLeftRadius: 0,
                  bottomRightRadius: 0,
                  color: "rgb(255, 255, 255)",
                  content: "0xcomingsoon",
                  fill: "rgb(0, 102, 255)",
                  font: {},
                  height: "100%",
                  id: "KBXBQ129K",
                  isMixedBorderRadius: false,
                  label: "Copy to Clipboard",
                  layoutId: "KBXBQ129K",
                  padding: 10,
                  paddingBottom: 10,
                  paddingLeft: 10,
                  paddingPerSide: false,
                  paddingRight: 10,
                  paddingTop: 10,
                  style: { height: "100%", width: "100%" },
                  success: "Copied!",
                  topLeftRadius: 0,
                  topRightRadius: 0,
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  dir: "auto",
                  style: {
                    "--font-selector": "R0Y7QmFuZ2Vycy1yZWd1bGFy",
                    "--framer-font-family": '"Bangers", sans-serif',
                  },
                  children: "CA : 0xcomingsoon",
                }),
              }),
              className: "framer-onpxpu",
              fonts: ["GF;Bangers-regular"],
              layoutDependency: layoutDependency,
              layoutId: "wrKLDAnYX",
              style: {
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  o20hHbw2z: {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        dir: "auto",
                        style: {
                          "--font-selector": "R0Y7QmFuZ2Vycy1yZWd1bGFy",
                          "--framer-font-family": '"Bangers", sans-serif',
                        },
                        children: "CA : COPIED!!!!",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-BmV2o.framer-i6yy7f, .framer-BmV2o .framer-i6yy7f { display: block; }",
  ".framer-BmV2o.framer-1mmltda { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-BmV2o .framer-1jajtaf { aspect-ratio: 0.868995633187773 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 34px); overflow: visible; position: relative; width: 30px; }",
  ".framer-BmV2o .framer-1ywu5on-container { bottom: 0px; flex: none; left: -43px; position: absolute; right: -19px; top: 0px; z-index: 1; }",
  ".framer-BmV2o .framer-onpxpu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 44
 * @framerIntrinsicWidth 369
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"o20hHbw2z":{"layout":["auto","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerHFYYL_Y6K = withCSS(Component, css, "framer-BmV2o");
export default FramerHFYYL_Y6K;
FramerHFYYL_Y6K.displayName = "copy";
FramerHFYYL_Y6K.defaultProps = { height: 44, width: 369 };
addPropertyControls(FramerHFYYL_Y6K, {
  variant: {
    options: ["cCoFZGODb", "o20hHbw2z"],
    optionTitles: ["Variant 1", "Variant 2"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerHFYYL_Y6K,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Bangers",
          source: "google",
          style: "normal",
          uiFamilyName: "Bangers",
          url: "https://fonts.gstatic.com/s/bangers/v25/FeVQS0BTqb0h60ACL5xa2bxii28.woff2",
          weight: "400",
        },
      ],
    },
    ...ClipboardFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerHFYYL_Y6K",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "44",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"o20hHbw2z":{"layout":["auto","fixed"]}}}',
        framerIntrinsicWidth: "369",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./HFYYL_Y6K.map
