// Generated by Framer (1ec61f0)
export default function metadata(params, activeLocale) {
  return {
    description:
      "The rocket emoji is the undisputed king of emojis used in the markets, being synonymous with parabolic proice growth. 🚀\n\nBorn from japanese mobile culture, it was quickly adopted by financial investors and is the king of hyping markets.",
    favicon:
      "/framerusercontent.com/assets/q3cxEVWW5JknPvGSnip00G1s.png",
    robots: "max-image-preview:large",
    socialImage:
      "/framerusercontent.com/assets/7qJpJ1nMUXY8FR6NsKuUW1vpz30.png",
    title: "ROCKET",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
